ALTER TABLE namatable1
ADD FOREIGN KEY (pk table1) REFERENCES namatable2 (pk table2)
ON UPDATE -- RESTRICT | CASCADE | SET NULL | NO ACTION | SET DEFAULT 
ON DELETE; -- RESTRICT | CASCADE | SET NULL | NO ACTION | SET DEFAULT